# Problem 1

In [7]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
a = np.random.randint(0,10, size = 5)
print(a)

# 3 - matris'in boyutunu öğrenin
print(a.shape)

# 4 - matris'i yeniden boyutlandırın

# 5 - matris'in boyut sayısını öğrenin
print(a.ndim)

[4 3 8 0 5]
(5,)
1


# Problem 2

In [14]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
b = np.arange(1,10)
print(b[::2])

# 2 - Oluşturduğunuz matrisi parçalayın
print(np.split(b,[3,5]))

# 3 - Parçalanmış matrisleri birleştirin
print(np.concatenate([b], axis =0))


[1 3 5 7 9]
[array([1, 2, 3]), array([4, 5]), array([6, 7, 8, 9])]
[1 2 3 4 5 6 7 8 9]


# Problem 3

In [22]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
sayilar = np.arange(5,101,2)
randomSayilar = np.random.choice(sayilar, size=10, replace=False)
print(np.reshape(randomSayilar, (5, 2)))

# 2 - matris'in özelliklerini inceleyin


[[17 85]
 [81 71]
 [73 55]
 [57 75]
 [83 65]]
