# Numpy

In [2]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
print(a*b)

[ 2  6 12 20]


.reshape() fonksiyonu ile arraylerin boyutunu değiştirebiliriz.

In [3]:
x = np.array([1,2,3,4,5,6,7,8,9])
multi = x.reshape(3,3)
print(multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


.shape ile arrayların boyutlarını öğrenebiliriz.

In [4]:
print(multi.shape)

(3, 3)


In [5]:
print(x.shape)

(9,)


.ndim ile arraylerin boyut sayısını öğrenebiliriz.

In [6]:
print(x.ndim)

1


In [7]:
print(multi.ndim)

2


# Birleştirme (Concatenation)
- .concatenate() fonksiyonu ile birleştirme yapabiliriz.

In [8]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
print(np.concatenate([x,y]))

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
z = np.array([11,12,13,14,15])
print(np.concatenate([x,y,z]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [10]:
a = np.array([[1,2,3],[4,5,6]])
print(np.concatenate([a,a]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [11]:
print(np.concatenate([a,a], axis =1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [12]:
print(np.concatenate([a,a], axis =0))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


- axis = 0 satır bazında birleştirme yapar.
- axis = 1 sütun bazında birleştirme yapar.

# Array Ayırma (Splitting)
- .split() fonksiyonu ile array ayırma yapabiliriz.

In [13]:
m = np.array([1,2,3,99,99,3,2,1])
print(np.split(m,[3,5]))

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]


In [14]:
a,b,c = np.split(m, [3,5])
print(a)
print(b)
print(c)

[1 2 3]
[99 99]
[3 2 1]


- vsplit() fonksiyonu ile array yatay olarak ayırma yapabiliriz.

In [16]:
n = np.arange(16).reshape(4,4)
np.vsplit(n, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

- hsplit() fonksiyonu ile array dikey olarak ayırma yapabiliriz.

In [17]:
np.hsplit(n, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

#### np.arange()
- Belli bir aralıkta sayıları oluşturmak için kullanılır.
- np.arange(start, stop, step)

In [19]:
np.arange(3,12,2)

array([ 3,  5,  7,  9, 11])

#### np.zeros()
- 0'lardan oluşan bir numpy dizisi oluşturulması için kullanılır.

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

#### np.ones()
- 1'lerden oluşan bir numpy dizisi oluşturulması için kullanılır.

In [21]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### np.linspace()
- Belirli bir aralıkta sayıları oluşturmak için kullanılır.
- np.linspace(başlangıç, bitiş, bölünecek aralık) 

In [22]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [23]:
np.random.randint(0,10,3)

array([4, 0, 9])

In [24]:
np.random.randint(2,22,5)

array([ 9, 13, 14,  2, 13])

In [25]:
npArray = np.arange(50)
npMulti = npArray.reshape(5,10)
print(npMulti.sum(axis = 1))

[ 45 145 245 345 445]


# Numpy Array'in Özellikleri
- ndim : Boyut sayısı
- shape : Boyut bilgisi
- size : Toplam eleman sayısı
- dtype : Veri tipi

In [27]:
a = np.random.randint(10, size = 10)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

1
(10,)
10
int32


# Array Sıralama (Sorting)
- Array sıralama işlemleri yapmak için numpy kütüphanesinde yer alan sort() fonksiyonu kullanılır.

In [29]:
v = np.array([8,24,232,12,5,42,55])
print(v)
v.sort()
print(v)

[  8  24 232  12   5  42  55]
[  5   8  12  24  42  55 232]


In [30]:
m = np.random.normal(20,5,(3,3))
print(m)

[[15.69691716 24.51062147 27.3111682 ]
 [21.41753609 25.42142602 26.1209744 ]
 [19.34359338 19.94612528 13.19120883]]


In [31]:
print(np.sort(m, axis=0))

[[15.69691716 19.94612528 13.19120883]
 [19.34359338 24.51062147 26.1209744 ]
 [21.41753609 25.42142602 27.3111682 ]]


In [32]:
print(np.sort(m, axis=1))

[[15.69691716 24.51062147 27.3111682 ]
 [21.41753609 25.42142602 26.1209744 ]
 [13.19120883 19.34359338 19.94612528]]


# Index ile Elemanlara Erişmek

In [33]:
a = np.random.randint(10, size = 10)
print(a[0])

1


In [34]:
print(a[-1])

5


In [35]:
a[0] = 100
print(a)

[100   0   0   9   0   1   2   5   0   5]


In [36]:
x = np.random.randint(10, size = (3,5))
print(x)

[[1 9 1 8 4]
 [1 6 7 3 6]
 [5 5 0 6 6]]


In [37]:
print(x[0,0])

1


In [38]:
print(x[1,1])

6


In [39]:
x[1,4] = 100
print(x)

[[  1   9   1   8   4]
 [  1   6   7   3 100]
 [  5   5   0   6   6]]


In [40]:
x[1,4] = 3.14
print(x)

[[1 9 1 8 4]
 [1 6 7 3 3]
 [5 5 0 6 6]]


# Slicing ile Elemanlara Erişmek

In [41]:
a = np.arange(20,30)
print(a)

[20 21 22 23 24 25 26 27 28 29]


In [42]:
print(a[0:3])

[20 21 22]


In [43]:
print(a[:3])

[20 21 22]


In [44]:
print(a[3:])

[23 24 25 26 27 28 29]


In [45]:
print(a[1::2])

[21 23 25 27 29]


In [46]:
b = np.random.randint(10, size = [5,5])
print(b)

[[6 7 2 5 2]
 [1 5 8 4 2]
 [1 1 7 4 3]
 [4 1 4 3 9]
 [9 0 6 2 7]]


In [47]:
print(b[:,0])

[6 1 1 4 9]


In [48]:
print(b[:,1])

[7 5 1 1 0]


In [49]:
print(b[0, :])

[6 7 2 5 2]


In [50]:
print(b[0:2 , 0:3])

[[6 7 2]
 [1 5 8]]


In [51]:
print(b[::2, ::2])

[[6 2 2]
 [1 7 3]
 [9 6 7]]


# Alt Küme Üzerinde İşlem Yapmak

In [52]:
alt_b = b[0:3 , 0:2]
alt_b

array([[6, 7],
       [1, 5],
       [1, 1]])

In [54]:
alt_b[0,0] = 100
alt_b[1,1] = 200
alt_b

array([[100,   7],
       [  1, 200],
       [  1,   1]])

In [55]:
print(b)

[[100   7   2   5   2]
 [  1 200   8   4   2]
 [  1   1   7   4   3]
 [  4   1   4   3   9]
 [  9   0   6   2   7]]


# Fancy Index
- Bir liste için bu arrayden istediğimiz indisleri koyarak o indislerdeki verileri alabiliriz.

In [56]:
v = np.arange(0, 30, 3)
print(v)

[ 0  3  6  9 12 15 18 21 24 27]


In [57]:
yetgen = [1,3,5]
print(v[yetgen])

[ 3  9 15]


In [58]:
m = np.arange(9).reshape(3,3)
satir = np.array([0,1])
sutun = np.array([1,2])
print(m[satir, sutun])

[1 5]


# Koşullu Eleman İşlemleri

In [59]:
v = np.array([1,2,3,4,5])
print(v > 3)

[False False False  True  True]


In [60]:
print(v[v>3])

[4 5]


In [61]:
print(v[v<3])

[1 2]


In [62]:
print(v[v>=3])

[3 4 5]


In [63]:
print(v[v<=3])

[1 2 3]


In [64]:
print(v[v!=3])

[1 2 4 5]


In [65]:
print(v[v==3])

[3]


# Matematiksel İşlemler

In [67]:
v = np.array([1,2,3,4,5])
print(v*2)

[ 2  4  6  8 10]


In [68]:
print(v+2)

[3 4 5 6 7]


In [69]:
print(v*5/10)

[0.5 1.  1.5 2.  2.5]


In [70]:
print(v**2)

[ 1  4  9 16 25]


In [72]:
print(np.subtract(v,3)) #Her bir elemandan 3 çıkartır.

[-2 -1  0  1  2]


In [74]:
print(np.add(v,2)) #toplama

[3 4 5 6 7]


In [75]:
np.multiply(v,2) #çarpma

array([ 2,  4,  6,  8, 10])

In [76]:
np.divide(v,2) #bölme

array([0.5, 1. , 1.5, 2. , 2.5])

In [77]:
np.power(v,2) #üs alma

array([ 1,  4,  9, 16, 25], dtype=int32)

In [78]:
np.mod(v,5) #mod alma

array([1, 2, 3, 4, 0], dtype=int32)

In [79]:
np.absolute(v) #mutlak değer işlemi

array([1, 2, 3, 4, 5])

In [81]:
print(np.sin(360))

0.9589157234143065


In [83]:
np.log(10)

2.302585092994046

# İki Bilinmeyenli Denklem Çözümü

In [85]:
# 5*x0 + x1 = 12
# x0 + 3*x1 = 10

a = np.array([[5,1], [1,3]])
b = np.array([12,10])
sonuc = np.linalg.solve(a,b)
print(sonuc)

[1.85714286 2.71428571]
