# Problem 1 

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
array = np.array([45, 6, 54, 244, 25])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
array.sort()
print(array)

[  6  25  45  54 244]


# Problem 2

In [1]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
import numpy as np
array1 = np.array([10,15,30,45,60])
print(array1)
print("--------------------------------------------")

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
array2 = np.arange(5, 16)
print(array2)
print("--------------------------------------------")

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
array3 = np.arange(50,100,5)
print(array3)
print("--------------------------------------------")

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
array4 = np.zeros(10)
print(array4)
print("--------------------------------------------")

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
array5 = np.ones(10)
print(array5)
print("--------------------------------------------")

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
array6 = np.linspace(0,100,6)
print(array6)
print("--------------------------------------------")

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
array7 = np.random.randint(10, 30, 5)
print(array7)
print("--------------------------------------------")

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
array8 = np.random.uniform(-1, 1, 10)
print(array8)
print("--------------------------------------------")

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matris1 = np.random.randint(10, 51, size = (3,5))
print(matris1)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
satirTop = np.sum(matris1, axis=1)
sutunTop = np.sum(matris1, axis=0)
print("Satır toplamları: ", satirTop)
print("Sütun toplamları: ", sutunTop)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
enBuyuk = np.max(matris1)
enKucuk = np.min(matris1)
ortalama = np.mean(matris1)

print("En büyük değer: ", enBuyuk)
print("En küçük değer: ", enKucuk)
print("Ortalama: ", ortalama)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
en_buyuk_indeks = np.argmax(matris1)
print("En büyük değerin indeksi: ", en_buyuk_indeks)
print("--------------------------------------------")

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
array9 = np.random.randint(10, 20, size=8)
print(array9[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(array9[::-1])
print("--------------------------------------------")

# 15- Üretilen matrisin ilk satırını seçiniz.
print(matris1[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(matris1[1,2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(matris1[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(matris1**2)
print("--------------------------------------------")

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
array10 = np.random.randint(-50, 50, size=(3,5))
print((array10 > 0) & (array10 % 2 == 0))

[10 15 30 45 60]
--------------------------------------------
[ 5  6  7  8  9 10 11 12 13 14 15]
--------------------------------------------
[50 55 60 65 70 75 80 85 90 95]
--------------------------------------------
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
--------------------------------------------
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
--------------------------------------------
[  0.  20.  40.  60.  80. 100.]
--------------------------------------------
[13 28 29 25 10]
--------------------------------------------
[ 8.68127947e-01  5.16969146e-01  3.42616495e-01  2.03652210e-02
 -2.91167477e-04 -7.92206953e-01  4.36114257e-01 -1.73813902e-02
 -2.93959274e-01  9.21395241e-02]
--------------------------------------------
[[33 19 25 48 35]
 [13 23 38 33 26]
 [10 36 18 23 15]]
Satır toplamları:  [160 133 102]
Sütun toplamları:  [ 56  78  81 104  76]
En büyük değer:  48
En küçük değer:  10
Ortalama:  26.333333333333332
En büyük değerin indeksi:  3
--------------------------------------------
[16 12